variable "aws_region" {}
variable "aws_profile" {}
variable "localip" {}
variable "db_instance_class" {}
variable "dbname" {}
variable "dbuser" {}
variable "dbpassword" {}
variable "public_key_path" {}
variable "key_name" {}